{
  try {
    this.fail(e.getCause());
  }
 catch (  Throwable e1) {
    LOG.debug(e1,e1);
  }
  super.exceptionCaught(ctx,e.getCause());
}
