{
  EventRecord.here(CallbackListenerSequence.class,EventType.CALLBACK,"fireException(" + t.getClass().getName() + ")").debug();
  for (  Callback.Checked<R> cb : this.failureCallbacks) {
    try {
      EventRecord.here(this.getClass(),EventType.CALLBACK,cb.getClass(),"fireException(" + t.getClass().getCanonicalName() + ")").debug();
      cb.fireException(t);
    }
 catch (    Throwable t2) {
      LOG.error("Exception occurred while trying to call: " + cb.getClass() + ".failure( "+ t.getMessage()+ " )");
      LOG.error(t2,t2);
    }
  }
}
