{
  for (  Callback cb : this.failureCallbacks) {
    try {
      LOG.debug(this.getClass().getSimpleName() + ":failure(" + t.getClass().getSimpleName()+ ") invoking callback: "+ cb.getClass().getSimpleName());
      cb.fire(t);
    }
 catch (    Throwable t2) {
      LOG.error("Exception occurred while trying to call: " + cb.getClass().getSimpleName() + ".failure( "+ t.getMessage()+ " )");
      LOG.error(t2,t2);
    }
  }
}
