{
  for (  Callback cb : this.failureCallbacks) {
    try {
      EventRecord.here(cb.getClass(),EventType.CALLBACK_LISTENER,"fireException(" + t.getClass().getSimpleName() + ")").debug();
      cb.fire(t);
    }
 catch (    Throwable t2) {
      LOG.error("Exception occurred while trying to call: " + cb.getClass().getSimpleName() + ".failure( "+ t.getMessage()+ " )");
      LOG.error(t2,t2);
    }
  }
}
