{
  if ((failure instanceof ExecutionException) && (failure.getCause() != null)) {
    failure=failure.getCause();
  }
  if (Callback.Checked.class.isAssignableFrom(this.callback.getClass())) {
    try {
      this.LOG.trace(EventRecord.here(this.callback.getClass(),EventType.CALLBACK,"fireException(" + failure.getClass().getSimpleName() + ")",failure.getMessage()));
      ((Checked)this.callback).fireException(failure);
    }
 catch (    final Throwable t) {
      this.LOG.error("BUG: an error occurred while trying to process an error.  Previous error was: " + failure.getMessage(),t);
    }
  }
 else   if (Callback.Completion.class.isAssignableFrom(this.callback.getClass())) {
    this.LOG.trace(EventRecord.here(this.callback.getClass(),EventType.CALLBACK,"fire(" + failure.getClass().getSimpleName() + ")",failure.getMessage()));
    ((Callback.Completion)this.callback).fire();
  }
}
