{
  RuntimeException rootCause=null;
  for (int i=0; i < CONCURRENT_UPDATE_RETRIES; i++) {
    try {
      return predicate.apply(arg);
    }
 catch (    RuntimeException ex) {
      if (Exceptions.isCausedBy(ex,OptimisticLockException.class)) {
        rootCause=Exceptions.causedBy(ex,OptimisticLockException.class);
        continue;
      }
 else {
        rootCause=ex;
        Logs.extreme().error(ex,ex);
        throw ex;
      }
    }
  }
  throw (rootCause != null ? rootCause : new NullPointerException("BUG: Transaction retry failed but root cause exception is unknown!"));
}
