{
  try {
    test2();
  }
 catch (  Exception e) {
    Debugging.logError(LOG,e,MARK + "Test failed");
  }
}
