{
  RuntimeException rootCause=null;
  for (int i=0; i < retries; i++) {
    try (final TransactionResource tx=Entities.transactionFor(this.entityType)){
      R ret=this.function.apply(input);
      tx.commit();
      return ret;
    }
 catch (    RuntimeException ex) {
      if (Exceptions.isCausedBy(ex,OptimisticLockException.class)) {
        rootCause=Exceptions.findCause(ex,OptimisticLockException.class);
      }
 else       if (Exceptions.isCausedBy(ex,LockAcquisitionException.class)) {
        rootCause=Exceptions.findCause(ex,LockAcquisitionException.class);
      }
 else {
        rootCause=ex;
        Logs.extreme().error(ex,ex);
        throw ex;
      }
      try {
        TimeUnit.MILLISECONDS.sleep(20);
      }
 catch (      InterruptedException ex1) {
        Exceptions.maybeInterrupted(ex1);
      }
      continue;
    }
  }
  throw (rootCause != null ? rootCause : new NullPointerException("BUG: Transaction retry failed but root cause exception is unknown!"));
}
