{
  RuntimeException rootCause=null;
  for (int i=0; i < retries; i++) {
    EntityTransaction db=Entities.get(this.entityType);
    try {
      R ret=this.function.apply(input);
      db.commit();
      return ret;
    }
 catch (    RuntimeException ex) {
      db.rollback();
      if (Exceptions.isCausedBy(ex,OptimisticLockException.class)) {
        rootCause=Exceptions.findCause(ex,OptimisticLockException.class);
        try {
          TimeUnit.MILLISECONDS.sleep(20);
        }
 catch (        InterruptedException ex1) {
          Exceptions.maybeInterrupted(ex1);
        }
        continue;
      }
 else {
        rootCause=ex;
        Logs.extreme().error(ex,ex);
        throw ex;
      }
    }
  }
  throw (rootCause != null ? rootCause : new NullPointerException("BUG: Transaction retry failed but root cause exception is unknown!"));
}
